language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mysql --execute "CREATE DATABASE IF NOT EXISTS \`forge\`;" --user=root
  - php artisan migrate --no-interaction -vvv

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true