language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

services:
  - mysql

env:
  - DB=mysql

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS forge;create database IF NOT EXISTS forge;'; fi"
  - php artisan migrate:install --no-interaction -vvv

script: phpunit

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true